enable container build in gitlab ci/cd

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -45,3 +45,31 @@ build:
         artifacts:
                 paths:
                         - mqtt-kafka-translator
+
+container_build:
+        stage: container
+        image:
+                name: cr.io/kaniko-project/executor:debug
+                entrypoint: [""]
+        tags:
+                - shared
+        before_script:
+                - echo $CI_DOCKER_CONFIG > /kaniko/.docker/config.json
+        cache: {}
+        script: |
+                if [ -z $CI_REGISTRY ] || [ -z $CI_REGISTRY_IMAGE ]; then
+                        echo "missing parameters please add CI_REGISTRY and/or CI_REGISTRY_IMAGE"
+                        exit 1
+                fi
+
+                if [ -z $CI_COMMIT_TAG ]; then
+                        version=$CI_COMMIT_SHA
+                else
+                        version=$CI_COMMIT_TAG
+                fi
+
+                /kaniko/executor \
+                        --context $CI_PROJECT_DIR \
+                        --dockerfile $CI_PROJECT_DIR/Dockerfile \
+                        --destination $CI_REGISTRY/$CI_REGISTRY_IMAGE:$version \
+                        --cache=true # Remove to disable caching
