Docker container build in ci

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -20,9 +20,41 @@ jobs:
         run: |
           make build
 
-      - name: Save kafka translator
+      - name: Save built binary
         uses: actions/upload-artifact@v3
         with:
-          name: mqtt-kafka-translator
-          path: mqtt-kafka-translator
-          retention-days: 2
+          name: connector
+          path: connector
+          retention-days: 1
+
+  container_build:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+
+    steps:
+      - name: Create config.json file for docker
+        run: |
+          echo $HARBOR_PROD_PUSH_ANALYSE_PLATFORM_KOSMOS > /kaniko/.docker/config.json
+
+      - name: Build docker container
+        uses: addnab/docker-run-action@v3
+        with:
+          registry: gcr.io
+          image: kaniko-project/executor:debug
+          run: |
+            if [ -z $CI_REGISTRY ] || [ -z $CI_REGISTRY_IMAGE ]; then
+                    echo "missing parameters please add CI_REGISTRY and/or CI_REGISTRY_IMAGE"
+                    exit 1
+            fi
+
+            if [ -z $CI_COMMIT_TAG ]; then
+                    version=$CI_COMMIT_SHA
+            else
+                    version=$CI_COMMIT_TAG
+            fi
+
+            /kaniko/executor \
+                    --context $CI_PROJECT_DIR \
+                    --dockerfile $CI_PROJECT_DIR/Dockerfile \
+                    --destination $CI_REGISTRY/$CI_REGISTRY_IMAGE:$version \
+                    --cache=true # Remove to disable caching
